notifications:
  email:
    on_success: never
    on_failure: change

stage: "Lint"
language: node_js
os: linux
node_js: "12"
env: 
  - PROJ="src"
  - PROJ="demo"
  - PROJ="demo-ng"
script: cd $PROJ && npm run ci.tslint

matrix:
  include:
    - stage: "Build"
      os: osx
      env:
        - Platform="iOS"
      osx_image: xcode10.2
      language: node_js
      node_js: "12"
      jdk: oraclejdk8
      script: cd demo && npm run build.plugin && tns build ios --bundle --env.uglify
    - language: android
      os: linux
      env:
        - Platform="Android"
      jdk: oraclejdk8
      script: cd demo && npm run build.plugin && tns build android --bundle --env.uglify --env.snapshot
    
    - stage: "Build Angular"
      os: osx
      env:
        - Platform="iOS"
      osx_image: xcode10.2
      language: node_js 
      node_js: "12"
      jdk: oraclejdk8
      script: cd demo-ng && npm run build.plugin && tns build ios --bundle --env.uglify
    - language: android
      os: linux
      env:
        - Platform="Android"
      jdk: oraclejdk8
      script: cd demo-ng && npm run build.plugin && tns build android --bundle --env.uglify --env.snapshot

before_install:
  - sudo pip install --ignore-installed --upgrade six # https://github.com/NativeScript/nativescript-cli/issues/3534
  - nvm install 12

install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
  - cd src && npm ci && cd ..

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - android-21
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'