notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "12"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: "WebPack and Build"
      os: osx
      env:
        - WebPack="iOS"
        - PYTHONPATH="/Library/Python/2.7/site-packages" # https://github.com/NativeScript/nativescript-cli/issues/3534
      osx_image: xcode10.2
      language: node_js 
      node_js: "12"
      jdk: oraclejdk8 
      script: cd demo && npm run build.plugin && npm ci && tns build ios --bundle --env.uglify
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 12
      script: cd demo && npm run build.plugin && npm ci && tns build android --bundle --env.uglify --env.snapshot

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - android-21
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
  